services:
  - type: web
    name: recoverai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_EMAIL
        value: batman.uses.ai@gmail.com
      - key: SMTP_PASSWORD
        value: "ason zvut pgju pnrr"
    plan: free
